# Generated by Django 4.0.6 on 2022-07-31 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_name', models.CharField(max_length=50)),
                ('history', models.TextField(null=True)),
                ('building_lat', models.FloatField(default=0.0)),
                ('building_lon', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('cafe', 'cafe'), ('restaurant', 'restaurant'), ('one-stop', 'one-stop'), ('book_return', 'book_return'), ('printer', 'printer'), ('lounge', 'lounge')], max_length=20)),
                ('facility_name', models.CharField(max_length=50)),
                ('facility_loc', models.TextField()),
                ('building_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KUMAPapp.building')),
            ],
        ),
        migrations.CreateModel(
            name='Entrance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrance_name', models.CharField(max_length=50)),
                ('entrance_time', models.TimeField()),
                ('entrance_lat', models.FloatField(default=0.0)),
                ('entrance_lon', models.FloatField(default=0.0)),
                ('building_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KUMAPapp.building')),
            ],
        ),
    ]
