# Generated by Django 4.1 on 2022-08-14 08:17

import KUMAPapp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_name', models.CharField(max_length=50)),
                ('history', models.TextField(null=True)),
                ('building_lat', models.FloatField(default=0.0)),
                ('building_lon', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('cafe', '카페'), ('restaurant', '식당'), ('one-stop', '원스톱'), ('book_return', '책반납기'), ('printer', '프린터'), ('lounge', '스터디')], max_length=20)),
                ('facility_name', models.CharField(max_length=50)),
                ('facility_loc', models.TextField(null=True)),
                ('building_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KUMAPapp.building')),
            ],
        ),
        migrations.CreateModel(
            name='Entrance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrance_name', models.CharField(max_length=50)),
                ('entrance_time', models.TextField(null=True)),
                ('entrance_lat', models.FloatField(default=0.0)),
                ('entrance_lon', models.FloatField(default=0.0)),
                ('entrance_num', models.IntegerField(null=True)),
                ('entrance_photo', models.ImageField(blank=True, null=True, upload_to=KUMAPapp.models.directory)),
                ('building_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KUMAPapp.building')),
            ],
        ),
    ]
