# Generated by Django 4.0.6 on 2022-08-04 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KUMAPapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrance',
            name='entrance_time',
        ),
        migrations.AddField(
            model_name='entrance',
            name='entrance_photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='entrance',
            name='entrance_time1',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='entrance',
            name='entrance_time2',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='facility_loc',
            field=models.TextField(null=True),
        ),
    ]
