# Generated by Django 4.0.6 on 2022-08-04 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KUMAPapp', '0002_remove_entrance_entrance_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrance',
            name='entrance_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
