# Generated by Django 4.0.6 on 2022-08-04 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KUMAPapp', '0003_alter_entrance_entrance_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrance',
            name='entrance_num',
            field=models.IntegerField(null=True),
        ),
    ]
