# Generated by Django 4.0.6 on 2022-08-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KUMAPapp', '0004_entrance_entrance_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrance',
            name='entrance_photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/image/<django.db.models.fields.related.ForeignKey>'),
        ),
    ]
