# Generated by Django 4.0.6 on 2022-08-04 11:46

import KUMAPapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KUMAPapp', '0005_alter_entrance_entrance_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrance',
            name='entrance_photo',
            field=models.ImageField(blank=True, null=True, upload_to=KUMAPapp.models.directory),
        ),
    ]
