# Generated by Django 4.0.6 on 2022-08-04 11:43

import MapApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MapApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrance',
            name='entrance_photo',
            field=models.ImageField(blank=True, null=True, upload_to=MapApp.models.directory),
        ),
    ]
