# Generated by Django 4.0.6 on 2022-08-04 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MapApp', '0003_alter_entrance_entrance_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrance',
            name='entrance_photo',
        ),
    ]
